---
- hosts: local
  connection: local
  vars:
    dbuser: redalert
    dbname: redalert
    dbpass: myreallyawesomepassword
  tasks:
################################################################################
#Install prerequisites
################################################################################
  - name: "Install packages"
    apt:
      name: "{{item}}"
      state: latest
    loop:
      - python3-pip
      - postgresql

  - name: "Install pip dependancies"
    pip:
      name: "{{item}}"
      executable: pip3
    loop:
      - psycopg2-binary
      - flask
      - slackclient
################################################################################
#Configure database
################################################################################
  - name: Configure postgresql for the first time
    shell: /var/lib/postgresql/10/bin/initdb /var/lib/postgresql/10/main/data > /var/lib/postgresql/10/main/initdb.log
    args:
      creates: /var/lib/postgresql/10/main/initdb.log
    become: true
    become_user: postgres

  - name: "Start and enable postgreSQL"
    systemd:
      name: postgresql
      state: started
      enabled: yes

  - name: "Create PostgreSQL user {{dbuser}}"
    postgresql_user:
      name: "{{dbuser}}"
      encrypted: yes
      #password: "md5({{dbpass}}{{dbuser}}|hash('md5'))"
      #echo "md5$(echo -n 'myreallyawesomepasswordredalert' | md5sum | awk '{print $1}')"
      password: md5f197f1f8bbcbf6c04cc16491c83a7800
    become: true
    become_user: postgres

  - name: "Create {{dbname}} postgreSQL database, owned by {{dbuser}}"
    postgresql_db:
      name: "{{dbname}}"
      owner: "{{dbuser}}"
    become: true
    become_user: postgres
################################################################################
#Copy application on server
################################################################################
  - name: "Copy Flask python application on server"
    copy:
      src: redalert.py
      dest: "/opt/redalert/redalert.py"
      mode: 0700
