apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "redalert.fullname" . }}
  labels:
    app: {{ template "redalert.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    paging: "false"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "redalert.name" . }}
        release: {{ .Release.Name }}
        paging: "false"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: "SLACK_BOT_TOKEN"
            value: "{{ .Values.redalert.slackBotToken }}"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/redalert
              readOnly: true            
          ports:
          - containerPort: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "redalert.fullname" . }}

