replicaCount: 1
image:
  repository: zwindler/redalert
  tag: latest
  pullPolicy: Always

service:
  fixed:
    enabled: false
    name: redalert
  type: ClusterIP
  externalPort: 3000
  internalPort: 3000
ingress:
  enabled: false

redalert:
  slackBotToken: "xoxb-your-own-slack-bot-token"
  files:
    config.py: |
      class Config(object):
          DEBUG = False
          SEVERITY_LEVELS = [
              {
                  "label": "Severity 1",
                  "value": "sev1"
              },
              {
                  "label": "Severity 2",
                  "value": "sev2"
              },
              {
                  "label": "Severity 3",
                  "value": "sev3"
              },
              {
                  "label": "Severity 4",
                  "value": "sev4"
              },
              {
                  "label": "Severity 5",
                  "value": "sev5"
              }
          ]
          INCLUDE_IN_INCIDENT = {
              "always" : [],
              "sev1" : [],
              "sev2" : [],
              "sev3" : [],
              "sev4" : [],
              "sev5" : []
          }     

resources: {}
  # If you do want to specify resources for redalert, uncomment the following 
  # lines, adjust them as necessary, and remove the curly braces after 
  # 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
